version: "3.8"

services:
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=chi_brows_stores_dev
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - chi-brows-stores-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql
      - PMA_PORT=3306
    depends_on:
      - mysql
    networks:
      - chi-brows-stores-network
    restart: unless-stopped

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    volumes:
      - ./server/public:/usr/src/app/public
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - chi-brows-stores-network
    restart: unless-stopped

  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://127.0.0.1:3000
    ports:
      - "80:80"
    depends_on:
      - server
    networks:
      - chi-brows-stores-network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  chi-brows-stores-network:
    driver: bridge
