
# Stage 1: Build
FROM node:20 AS builder

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build

# Stage 2: Runtime only
FROM node:20

WORKDIR /usr/src/app


COPY package*.json ./
RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/views ./views
# COPY --from=builder /app/src/config/credentials.json ./src/config/credentials.json

EXPOSE 3000
CMD ["node", "dist/src/main"]